# Generated by Django 4.1.3 on 2022-11-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='services',
            field=models.ManyToManyField(related_name='services', to='account.services'),
        ),
    ]
