# Generated by Django 4.1.3 on 2022-11-13 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_services_user_profile_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='About your self'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Where achievent occured')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='E.e Jomo kenyatta University Of Agriculture and technology')),
                ('year', models.DateField(blank=True, default=datetime.datetime(2022, 11, 13, 18, 36, 29, 715716), null=True, verbose_name='Achievement Date')),
                ('achievement', models.CharField(blank=True, max_length=100, null=True, verbose_name='MDS')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='For, Awards')),
                ('body', models.CharField(blank=True, max_length=800, null=True, verbose_name='For, Awards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='account.profile')),
            ],
        ),
    ]
