# Generated by Django 4.1.3 on 2022-11-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_achievement_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stage ie Education, work etc'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Where achievent occured E.e Jomo kenyatta University Of Agriculture and technology'),
        ),
    ]
