# Generated by Django 4.1.3 on 2022-11-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_achievement_level_alter_achievement_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special', models.CharField(blank=True, max_length=100, null=True, verbose_name='Example Orthodentist')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='specializations',
            field=models.ManyToManyField(blank=True, null=True, related_name='specialization', to='account.specialization'),
        ),
    ]
