# Generated by Django 4.1.3 on 2022-11-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_specialization_profile_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='specialization', to='account.specialization'),
        ),
    ]
