# Generated by Django 4.1.3 on 2022-11-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='specializations', to='account.specialization'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='special',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Example Orthodentist'),
        ),
    ]
