# Generated by Django 4.1.3 on 2022-11-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_profile_specializations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of study')),
                ('start_year', models.DateField(auto_now=True, verbose_name='Start Date')),
                ('end_year', models.DateField(auto_now=True, verbose_name='End Date')),
                ('course', models.CharField(blank=True, max_length=200, null=True, verbose_name='Course Studied')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='account.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
