# Generated by Django 4.1.3 on 2022-11-13 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_education_delete_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExpirience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Work')),
                ('start_year', models.DateField(auto_now=True, verbose_name='Start Date')),
                ('end_year', models.DateField(auto_now=True, verbose_name='End Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workexpirience', to='account.profile')),
            ],
        ),
    ]
