# Generated by Django 4.1.3 on 2022-11-13 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_workexpirience'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website Link'),
        ),
        migrations.AddField(
            model_name='workexpirience',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website Link'),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of tyhe award')),
                ('year', models.DateField(auto_now=True, verbose_name='Date Awarded')),
                ('desc', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='account.profile')),
            ],
        ),
    ]
