# Generated by Django 4.1.3 on 2022-11-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_education_website_workexpirience_website_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.DateField(verbose_name='Date Awarded'),
        ),
        migrations.AlterField(
            model_name='workexpirience',
            name='end_year',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='workexpirience',
            name='start_year',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
