# Generated by Django 4.1.3 on 2022-11-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_award_year_alter_workexpirience_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
