# Generated by Django 4.1.3 on 2022-11-13 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_education_end_year_alter_education_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.DateField(blank=True, verbose_name='Date Awarded'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='workexpirience',
            name='end_year',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='workexpirience',
            name='start_year',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
