# Generated by Django 4.1.3 on 2022-11-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_profile_is_subscribed_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewDoctor',
        ),
    ]
