# Generated by Django 4.1.3 on 2022-11-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_reviewdoctor_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdoctor',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
