# Generated by Django 4.1.3 on 2022-11-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_reviewdoctor_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewDoctor',
            new_name='ProfileReview',
        ),
    ]
