# Generated by Django 4.1.3 on 2022-11-14 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_rename_reviewdoctor_profilereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilereview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_reviewer', to='account.profile'),
        ),
    ]
