# Generated by Django 4.1.2 on 2022-11-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_profilereview_reviewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinician',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Female',
        ),
        migrations.DeleteModel(
            name='Male',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Pharmacist',
        ),
        migrations.AlterModelOptions(
            name='profilereview',
            options={'get_latest_by': ['pub_date'], 'ordering': ['-pub_date']},
        ),
    ]
