# Generated by Django 4.1.3 on 2022-11-15 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_delete_clinician_delete_doctor_delete_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Please enter a valide phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
