# Generated by Django 4.1.3 on 2022-11-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0023_delete_clinician_delete_doctor_delete_female_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('core_services', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('PHARM', 'Pharmacy'), ('CLINIC', 'Clinic'), ('LAB', 'Laboratory')], default='PHARM', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('pro_pic', models.ImageField(blank=True, null=True, upload_to='upload/facilities/')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='96 Red Hawk Road Cyrus, MN 56323')),
                ('about', models.CharField(max_length=1000)),
                ('average_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Clinics Phone Number')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_owner', to='account.profile')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['name', 'location'],
                'get_latest_by': 'registration_date',
            },
        ),
        migrations.CreateModel(
            name='FacilityBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('TANZANIA', 'Tanzania'), ('UGANDA', 'Uganda'), ('KENYA', 'Kenya'), ('SOUTH AFRICA', 'South Africa')], default='KENYA', max_length=30, verbose_name='Facility Branches')),
                ('address', models.CharField(max_length=100, verbose_name='96 Red Hawk Road Cyrus')),
                ('branch_pic', models.ImageField(blank=True, null=True, upload_to='upload/branches/main/')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area of specialization,i.e Neurology')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_branch', to='core.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, verbose_name='i.e screening')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('M', 'Monday'), (' T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('SU', 'Sunday')], default='M', max_length=2, null=True, verbose_name='Operational Days; Monday')),
                ('openning_time', models.TimeField(auto_now=True)),
                ('closing_time', models.TimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_working_day', to='core.facilitybranch')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_day', to='core.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('review', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to='account.profile')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_review', to='core.facility')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='users/facility/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_pic', to='core.facility')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='services',
            field=models.ManyToManyField(related_name='facility_services', to='core.service'),
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='uploads/location/branch/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_image', to='core.facilitybranch')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('about', models.CharField(max_length=500)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facility')),
            ],
        ),
    ]
