# Generated by Django 4.1.3 on 2022-11-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiabledAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('date_joined', models.DateTimeField()),
                ('date_left', models.DateTimeField()),
                ('acc_type', models.CharField(max_length=20)),
            ],
        ),
    ]
