# Generated by Django 4.1.3 on 2022-11-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabledAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabledaccount',
            name='acc_type',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='diabledaccount',
            name='account_name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='diabledaccount',
            name='date_joined',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='diabledaccount',
            name='date_left',
            field=models.DateTimeField(editable=False),
        ),
    ]
