# Generated by Django 4.1.3 on 2022-11-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabledAccount', '0002_alter_diabledaccount_acc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabledaccount',
            name='account_name',
            field=models.EmailField(editable=False, max_length=200),
        ),
    ]
